### PR TITLE
Fix compilation with ghc-8.2.1-rc3

### LINKED ISSUE #13: Fails to compile with GHC-8.2.1-rc3
Using https://gist.github.com/tfausak/623d283cfe7a338bcbfca56ddfec0ecd I get the following error:

```
    /run/user/499/stack2779/log-warper-1.1.2/src/System/Wlog/CanLog.hs:70:13: error:
        • The default type signature for dispatchMessage:
            forall (t :: (* -> *) -> * -> *) (n :: * -> *).
            (MonadTrans t, t n ~ m, CanLog n) =>
            LoggerName -> Severity -> Text -> t n ()
          does not match its corresponding non-default type signature
        • When checking the class method:
            dispatchMessage :: forall (m :: * -> *).
                               CanLog m =>
                               LoggerName -> Severity -> Text -> m ()
          In the class declaration for ‘CanLog’
       |
    70 |     default dispatchMessage :: (MonadTrans t, t n ~ m, CanLog n)
       |             ^^^^^^^^^^^^^^^
```

cc @ChShersh @volhovM

### PR DESCRIPTION
**Pull request by chshersh**
This should fix #13.

### CODE REVIEW

**Comment by domenkozar** [comment]
Another instance in master (was using log-warper-1.1.2 previously): 

```
    /home/ielectric/dev/serokell/daedalus/cardano-sl/.stack-work/downloaded/47Tbx2KoHCkx/src/System/Wlog/LoggerNameBox.hs:52:55: error:
        Ambiguous occurrence ‘StateT’
        It could refer to either ‘Universum.StateT’,
                                 imported from ‘Universum’ at src/System/Wlog/LoggerNameBox.hs:32:1-26
                                 (and originally defined in ‘Control.Monad.Trans.State.Lazy’)
                              or ‘Control.Monad.State.Strict.StateT’,
                                 imported from ‘Control.Monad.State.Strict’ at src/System/Wlog/LoggerNameBox.hs:27:59-64
                                 (and originally defined in ‘Control.Monad.Trans.State.Strict’)
       |
    52 | instance (Monad m, HasLoggerName m) => HasLoggerName (StateT a m) where
       |                                                       ^^^^^^
```

**Comment by chshersh** [comment]
@domenkozar This error with `StateT` due to `universum` update. `log-warper` uses `universum-0.5`. I fixed that error in `log-warper-1.1.4` within this commit: https://github.com/serokell/log-warper/commit/1d0b8790771e710ee548944f4a49bf3904e7ef2b

**Comment by domenkozar** [comment]
OK, with `universum-0.5` it compiles. Should we update other packages for universum-0.5?

**Comment by chshersh** [comment]
@domenkozar Yes, I think we should update `cardano-sl` to `universum-0.5`. This should be not so difficult refactoring task but some errors may occur.

**Comment by domenkozar** [comment]
Thanks - I have also opened https://github.com/serokell/time-warp-nt/issues/82
