### ISSUE TITLE
Fails to compile on GHC 8.0.2-rc1

### ISSUE THREAD

**Issue by domenkozar** [serokell/log-warper#1]
```
src/System/Wlog/CanLog.hs:68:10: error:
    • Couldn't match type ‘m’ with ‘LoggerNameBox m’
      ‘m’ is a rigid type variable bound by
        the instance declaration at src/System/Wlog/CanLog.hs:68:10
      Expected type: LoggerName -> Severity -> Text -> LoggerNameBox m ()
        Actual type: LoggerName
                     -> Severity -> Text -> LoggerNameBox (LoggerNameBox m) ()
    • In the expression:
        System.Wlog.CanLog.$dmdispatchMessage @LoggerNameBox m
      In an equation for ‘dispatchMessage’:
          dispatchMessage
            = System.Wlog.CanLog.$dmdispatchMessage @LoggerNameBox m
      In the instance declaration for ‘CanLog (LoggerNameBox m)’
    • Relevant bindings include
        dispatchMessage :: LoggerName
                           -> Severity -> Text -> LoggerNameBox m ()
          (bound at src/System/Wlog/CanLog.hs:68:10)

src/System/Wlog/CanLog.hs:69:10: error:
    • Couldn't match type ‘m’ with ‘ReaderT r m’
      ‘m’ is a rigid type variable bound by
        the instance declaration at src/System/Wlog/CanLog.hs:69:10
      Expected type: LoggerName -> Severity -> Text -> ReaderT r m ()
        Actual type: LoggerName
                     -> Severity -> Text -> ReaderT r (ReaderT r m) ()
    • In the expression:
        System.Wlog.CanLog.$dmdispatchMessage @ReaderT r m
      In an equation for ‘dispatchMessage’:
          dispatchMessage
            = System.Wlog.CanLog.$dmdispatchMessage @ReaderT r m
      In the instance declaration for ‘CanLog (ReaderT r m)’
    • Relevant bindings include
        dispatchMessage :: LoggerName -> Severity -> Text -> ReaderT r m ()
          (bound at src/System/Wlog/CanLog.hs:69:10)

src/System/Wlog/CanLog.hs:70:10: error:
    • Couldn't match type ‘m’ with ‘StateT s m’
      ‘m’ is a rigid type variable bound by
        the instance declaration at src/System/Wlog/CanLog.hs:70:10
      Expected type: LoggerName -> Severity -> Text -> StateT s m ()
        Actual type: LoggerName
                     -> Severity -> Text -> StateT s (StateT s m) ()
    • In the expression:
        System.Wlog.CanLog.$dmdispatchMessage @StateT s m
      In an equation for ‘dispatchMessage’:
          dispatchMessage = System.Wlog.CanLog.$dmdispatchMessage @StateT s m
      In the instance declaration for ‘CanLog (StateT s m)’
    • Relevant bindings include
        dispatchMessage :: LoggerName -> Severity -> Text -> StateT s m ()
          (bound at src/System/Wlog/CanLog.hs:70:10)
```

cc @ChShersh

**Comment by domenkozar** [comment]
Obeying type checker just won't work:

```

src/System/Wlog/CanLog.hs:68:10: error:
    • Couldn't match type ‘m’ with ‘LoggerNameBox m’
      ‘m’ is a rigid type variable bound by
        the instance declaration at src/System/Wlog/CanLog.hs:68:10
      Expected type: LoggerName
                     -> Severity -> Text -> LoggerNameBox (LoggerNameBox m) ()
        Actual type: LoggerName
                     -> Severity
                     -> Text
                     -> LoggerNameBox (LoggerNameBox (LoggerNameBox m)) ()
    • In the expression:
        System.Wlog.CanLog.$dmdispatchMessage
          @LoggerNameBox (LoggerNameBox m)
      In an equation for ‘dispatchMessage’:
          dispatchMessage
            = System.Wlog.CanLog.$dmdispatchMessage
                @LoggerNameBox (LoggerNameBox m)
      In the instance declaration for
        ‘CanLog (LoggerNameBox (LoggerNameBox m))’
    • Relevant bindings include
        dispatchMessage :: LoggerName
                           -> Severity -> Text -> LoggerNameBox (LoggerNameBox m) ()
          (bound at src/System/Wlog/CanLog.hs:68:10)

src/System/Wlog/CanLog.hs:69:10: error:
    • Couldn't match type ‘m’ with ‘ReaderT r m’
      ‘m’ is a rigid type variable bound by
        the instance declaration at src/System/Wlog/CanLog.hs:69:10
      Expected type: LoggerName
                     -> Severity -> Text -> ReaderT r (ReaderT r m) ()
        Actual type: LoggerName
                     -> Severity -> Text -> ReaderT r (ReaderT r (ReaderT r m)) ()
    • In the expression:
        System.Wlog.CanLog.$dmdispatchMessage @ReaderT r (ReaderT r m)
      In an equation for ‘dispatchMessage’:
          dispatchMessage
            = System.Wlog.CanLog.$dmdispatchMessage @ReaderT r (ReaderT r m)
      In the instance declaration for ‘CanLog (ReaderT r (ReaderT r m))’
    • Relevant bindings include
        dispatchMessage :: LoggerName
                           -> Severity -> Text -> ReaderT r (ReaderT r m) ()
          (bound at src/System/Wlog/CanLog.hs:69:10)

src/System/Wlog/CanLog.hs:70:10: error:
    • Couldn't match type ‘m’ with ‘StateT s m’
      ‘m’ is a rigid type variable bound by
        the instance declaration at src/System/Wlog/CanLog.hs:70:10
      Expected type: LoggerName
                     -> Severity -> Text -> StateT s (StateT s m) ()
        Actual type: LoggerName
                     -> Severity -> Text -> StateT s (StateT s (StateT s m)) ()
    • In the expression:
        System.Wlog.CanLog.$dmdispatchMessage @StateT s (StateT s m)
      In an equation for ‘dispatchMessage’:
          dispatchMessage
            = System.Wlog.CanLog.$dmdispatchMessage @StateT s (StateT s m)
      In the instance declaration for ‘CanLog (StateT s (StateT s m))’
    • Relevant bindings include
        dispatchMessage :: LoggerName
                           -> Severity -> Text -> StateT s (StateT s m) ()
          (bound at src/System/Wlog/CanLog.hs:70:10)
```

**Comment by chshersh** [comment]
Fixed in this commit: https://github.com/serokell/log-warper/commit/c9f33c01c72da066a1de3af953ef7d8d506f3a88
Closing issue
